### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by Ariana8456** [enghock1/Real-Time-2D-and-3D-Hand-Pose-Estimation#1]
Hi, I want to know what are  evaluation_K.json and evaluation_scale.json's function ? How to obtain the file when testing other pictures?Could you explain the two file's mean?Thanks.

**Comment by enghock1** [comment]
Hi,

To answer your question:

The K parameter (3x3 matrix) is the intrinsic parameter of a camera. Normally, the K parameter is provided for every image in the image dataset (such as FreiHAND and STB dataset). However, in the case where you want to test your own hand image, you need to obtain the K parameter of your camera (or webcam). Check out this [link](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html) or go to the camera_parameter_K folder on how to obtain the K parameter of your camera.

On the other hand, the scale parameter is the length of the reference bone (though I am not sure which bone in the hand it refers). It is used to identify the scale of the hand with respect to the image. For testing my own image, I just set it as 0.03 (~3cm).

Thanks.
