### ISSUE TITLE
How do I test my personal images?

### ISSUE THREAD

**Issue by Wu-Jin-tao** [enghock1/Real-Time-2D-and-3D-Hand-Pose-Estimation#3]
How do I test my personal images

**Comment by enghock1** [comment]
The easiest way to test your own images is to modify 7.real_time_3D_handpose_estimation.py script to load and test your own images rather than running real-time using the webcam. 

Also, you first need to obtain the K parameter of your camera used to take the images (see camera_parameter_K folder).
