### ISSUE TITLE
dual hand estimation

### ISSUE THREAD

**Issue by lisa676** [enghock1/Real-Time-2D-and-3D-Hand-Pose-Estimation#4]
Thanks for this meaningful repository. I have a question that how it can work with left and right hand at same time?
Do we need additional training on other datasets for this step? 
Need your suggestions about it. Thanks

**Comment by enghock1** [comment]
Hi there, this model would not work on both hands at the same time, but you can apply some tricks to make it work (sort of). One way I can think of, for non-interacting hand case, is to have a simple ML model to identify and crop the hands before passing them to the hand pose estimation model, then project the estimated hand skeletons back to the original image. Obviously, this trick would not work for the interacting hand case, and you might need a new dataset with both hands and a new DL architecture to make it work.
